#The name of your workflow.
name:  master
# Trigger the workflow on push to master
on:
  push:
    branches:
      - master
#A workflow run is made up of one or more jobs. Jobs run in parallel by default.
jobs:
  build_android_release:
    #if conditional to prevent a job from r
    runs-on: ubuntu-latest
    name: Build and deploy apk for Android
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.10.3'
      # This action sets up a java environment
      # https://github.com/actions/setup-java
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - run: flutter pub get
      # build Android version
      - name: Decrypt signing key and firebase config
        run: ./.github/scripts/decrypt_secret_android.sh
        env:
          ANDROID_DEPLOY_KEY_SECRET_PASSPHRASE: ${{ secrets.ANDROID_DEPLOY_KEY_SECRET_PASSPHRASE }}
          KEY_PROPERTIES_SECRET_PASSPHRASE: ${{ secrets.KEY_PROPERTIES_SECRET_PASSPHRASE }}
          ANDROID_GOOGLE_JSON_ENCRYPTION_SECRET: ${{ secrets.ANDROID_GOOGLE_JSON_ENCRYPTION_SECRET }}
      - name: Move decrypted files to their correct locations
        run: |
          mv $HOME/secrets/key.jks $GITHUB_WORKSPACE/android/app/key.jks
          mv $HOME/secrets/key.properties $GITHUB_WORKSPACE/android/key.properties
          mv $HOME/secrets/google-services.json $GITHUB_WORKSPACE/android/app/google-services.json
      - name: Build Android app
        run: flutter build apk --release --target-platform android-arm,android-arm64,android-x64 --build-number=$GITHUB_RUN_ID
      # - name: upload artifact to Firebase App Distribution
      #   uses: wzieba/Firebase-Distribution-Github-Action@v1
      #   with:
      #     appId: ${{secrets.FIREBASE_ANDROID_APP_ID}}
      #     token: ${{secrets.FIREBASE_TOKEN}}
      #     groups: androidtesters
      #     file: build/app/outputs/flutter-apk/app-release.apk
  
  build_ios_release:
    #if conditional to prevent a job from running
    runs-on: macos-11
    #Identifies any jobs that must complete successfully before this job will run.
    name: Build .ipa for iOS
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.10.3'
      - run: flutter pub get
      # setup encrypted files
      - name: Decrypt firebase config
        run: ./.github/scripts/decrypt_secret_ios.sh
        env:
          IOS_GOOGLE_PLIST_ENCRYPTION_SECRET: ${{ secrets.IOS_GOOGLE_PLIST_ENCRYPTION_SECRET }}
      - name: Move decrypted files to their correct locations
        run: |
          mv $HOME/secrets/GoogleService-Info.plist $GITHUB_WORKSPACE/ios/GoogleService-Info.plist
      # build iOS version
      - name: Build Unsigned iOS App
        run: |
          pod repo update
          flutter build ios --release --no-codesign --build-number=$GITHUB_RUN_ID
      - name: Sign iOS App
        uses: maierj/fastlane-action@v1.2.0
        env:
          MATCH_GIT_BASIC_AUTHORIZATION: ${{ secrets.MATCH_GIT_BASIC_AUTH }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
        with:
          # The lane that should be executed.
          lane: build
          # The relative path from the project root directory to the subdirectory where the fastlane folder is located.
          subdirectory: ios
          # The action tracks usage in Firebase by default. You can disable tracking by setting this parameter to 'true'.
          skip-tracking: true
      - name: Upload build artifact to deploy using linux
        uses: actions/upload-artifact@v2
        with:
          name: ios-app-release
          path: ios/Runner.ipa
  deploy_ios_release:
    runs-on: ubuntu-latest
    name:  Deploy ipa for iOS to firebase
    needs: build_ios_release
    steps:
      - name: Download iOS artifact to deploy to firebase
        uses: actions/download-artifact@v2
        with:
          name: ios-app-release
      - name: upload artifact to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{secrets.FIREBASE_IOS_APP_ID}}
          token: ${{secrets.FIREBASE_TOKEN}}
          groups: iostesters
          file: Runner.ipa
  deploy_web:
    name: Build and deploy website
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.10.3'
      - run: flutter pub get && flutter build web
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_RECIPES_8957C }}"
          projectId: recipes-8957c
          channelId: live